from pathlib import Path
import shutil

repo = Path('.')
# The web bundle is regenerated by `npm run build && npx cap sync ios`.
shutil.rmtree(repo / 'ios/App/App/public', ignore_errors=True)
# The native lock-screen notification uses the short notification WAV, not the long playback WAV.
for path in [repo / 'ios/App/App/adhan.wav', repo / 'public/audio/adhan.wav']:
    path.unlink(missing_ok=True)

pbx = repo / 'ios/App/App.xcodeproj/project.pbxproj'
lines = pbx.read_text().splitlines()
lines = [line for line in lines if 'adhan.wav' not in line]
pbx.write_text('\n'.join(lines) + '\n')
print('removed generated iOS web assets and duplicate long WAV files')
